/* TinyML Runtime – public API  (integer‑only, zero float types).
 *
 * Lightweight handle‑based INT8 inference engine for TMDL models
 * generated by the TinyML compiler.  The library contains **no**
 * ``float`` or ``double`` types anywhere.
 *
 * Usage sketch::
 *
 *     TinyML *ml = TinyML_Create(&mem_if, model_data);
 *     int8_t  output[10];
 *     TinyML_Run(ml, input_int8, output);
 *     // output[argmax] == predicted class, output[i] == 0 for i≠max
 *     TinyML_Destroy(ml);
 */
#ifndef TINYML_H
#define TINYML_H

#include "arena/arena.h"
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define TML_OK 0
#define TML_ERR -1
#define TML_ERR_MAGIC -2
#define TML_ERR_MDLTYPE -3
#define TML_ERR_OOM -4
#define TML_ERR_LAYER -5
#define TML_ERR_DIMS -6
#define TML_ERR_PARAM -7

typedef struct TinyML *TinyMLHandle;

/**
 * Create a TinyML runtime instance.
 *
 * @param arena Memory interface.
 * @param model Pointer to compiled TMDL model binary.
 * @return      Opaque handle, or NULL on error.
 */
TinyMLHandle TinyML_Create(ArenaHandle arena, const uint8_t *model);

/** Destroy a runtime instance. */
void TinyML_Destroy(TinyMLHandle self);

/**
 * Run inference (integer‑only).
 *
 * The output uses a simplified arg‑max softmax:
 *   ``output[argmax] = 127``, ``output[i≠argmax] = 0``.
 *
 * @param self   Runtime handle.
 * @param input  Input data, INT8 HWC layout.
 * @param output Output buffer, at least ``TinyML_GetOutputSize`` bytes.
 * @return       TML_OK on success, negative error code otherwise.
 */
int TinyML_Run(TinyMLHandle self, const int8_t *input, int8_t *output);

/** Return number of input elements (H × W × C). */
int TinyML_GetInputSize(TinyMLHandle self);

/** Return number of output elements. */
int TinyML_GetOutputSize(TinyMLHandle self);

#ifdef __cplusplus
}
#endif

#endif /* TINYML_H */
