/* TinyML Runtime – public API.
 *
 * Provides a lightweight, handle‑based INT8 inference engine for TMDL
 * models generated by the TinyML compiler.  Only the soft CPU backend
 * is included.
 *
 * Usage sketch::
 *
 *     TinyML *ml = TinyML_Create(&mem_if, model_data);
 *     TinyML_Run(ml, input_int8_data, output_float_data);
 *     TinyML_Destroy(ml);
 */
#ifndef TINYML_H
#define TINYML_H

#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------ */
/*  Error codes                                                        */
/* ------------------------------------------------------------------ */

#define TML_OK            0
#define TML_ERR          -1
#define TML_ERR_MAGIC    -2
#define TML_ERR_MDLTYPE  -3
#define TML_ERR_OOM      -4
#define TML_ERR_LAYER    -5
#define TML_ERR_DIMS     -6
#define TML_ERR_PARAM    -7

/* ------------------------------------------------------------------ */
/*  Opaque handle                                                      */
/* ------------------------------------------------------------------ */

typedef struct TinyML_ TinyML;

/* ------------------------------------------------------------------ */
/*  Memory interface (included for convenience – also defined in       */
/*  lib/interface/memory_if.h)                                          */
/* ------------------------------------------------------------------ */

#ifndef _MEMORY_IF_H
typedef void *(*tml_mem_alloc_t)(void *self, size_t size);
typedef void  (*tml_mem_free_t) (void *self, void *addr);

typedef struct memory_if {
    void            *self;
    tml_mem_alloc_t  mem_alloc;
    tml_mem_free_t   mem_free;
} memory_if;
#endif

/* ------------------------------------------------------------------ */
/*  API                                                                */
/* ------------------------------------------------------------------ */

/**
 * Create a TinyML runtime instance.
 *
 * @param mem    Memory interface for internal buffer allocation.
 *               May be NULL – then ``malloc`` / ``free`` are used.
 * @param model  Pointer to the compiled TMDL model binary (in flash/RAM).
 * @return       Opaque handle, or NULL on error.
 */
TinyML *TinyML_Create(const memory_if *mem, const uint8_t *model);

/**
 * Destroy a runtime instance, freeing the internal buffer.
 */
void TinyML_Destroy(TinyML *self);

/**
 * Run inference.
 *
 * @param self   Runtime handle.
 * @param input  Input data in INT8 format, layout HWC (or flattened).
 * @param output Output buffer – receives dequantised float results.
 * @return       TML_OK on success, negative error code otherwise.
 */
int TinyML_Run(TinyML *self, const int8_t *input, float *output);

/** Return the number of input elements (H*W*C). */
int TinyML_GetInputSize(TinyML *self);

/** Return the number of output elements. */
int TinyML_GetOutputSize(TinyML *self);

#ifdef __cplusplus
}
#endif

#endif /* TINYML_H */
